// /src/config/apiRoutes.ts

export const apiRoutes = {
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        LOGOUT: '/auth/logout',
        ME: '/auth/me',
        MY_PERMISSIONS: '/auth/my-permissions',
        USERS: '/users',
        UPDATE: '/users/profile',
    },
    WORKSPACES: {
        BASE: '/workspaces',
        BY_ID: (id: string) => `/workspaces/${id}`,
        UPDATE: (id: string) => `/workspaces/${id}`,
        MEMBERS: (id: string) => `/workspaces/${id}/members`,
        ADD_MEMBER: (id: string) => `/workspaces/${id}/members`,
        REMOVE_MEMBER: (id: string, userId: string) => `/workspaces/${id}/members/${userId}`,
        UPDATE_MEMBER: (id: string, userId: string) => `/workspaces/${id}/members/${userId}`,
        INVITE: '/invite/send',
    },
    PROJECTS: {
        BASE: '/projects',
        BY_ID: (id: string) => `/projects/${id}`,
        MEMBERS: (id: string) => `/projects/${id}/members`,
        ADD_MEMBER: (id: string) => `/projects/${id}/members`,
        REMOVE_MEMBER: (id: string, userId: string) => `/projects/${id}/members/${userId}`,
        UPDATE_MEMBER: (id: string, userId: string) => `/projects/${id}/members/${userId}`,
    },
    BOARDS: {
        BASE: '/boards',
        BY_ID: (id: string) => `/boards/${id}`,
        COLUMNS: (id: string) => `/boards/${id}/columns`,
    },
    TASKS: {
        BASE: '/tasks',
        BY_ID: (id: string) => `/tasks/${id}`,
        BY_KEY: (key: string) => `/tasks/key/${key}`,
        BY_PROJECT: (projectId: string) => `/tasks/project/${projectId}`,
        BY_SPRINT: (sprintId: string) => `/tasks/sprint/${sprintId}`,
        BY_BOARD: (boardId: string) => `/tasks/board/${boardId}`,
        ASSIGNEE: (userId: string) => `/tasks/assignee/${userId}`,
        MOVE: (id: string) => `/tasks/${id}/move`,
        ASSIGN: (id: string) => `/tasks/${id}/assign`,
        STATUS: (id: string) => `/tasks/${id}/status`,
        LABELS: (id: string) => `/tasks/${id}/labels`,
    },
    SPRINTS: {
        BASE: '/sprints',
        BY_ID: (id: string) => `/sprints/${id}`,
        START: (id: string) => `/sprints/${id}/start`,
        COMPLETE: (id: string) => `/sprints/${id}/complete`,
    },
    WORKFLOWS: {
        BASE: '/workflows',
        BY_ID: (id: string) => `/workflows/${id}`,
        BY_PROJECT: (projectId: string) => `/workflows/project/${projectId}`,
        CREATE_DEFAULT: (projectId: string) => `/workflows/default/${projectId}`,
        TRANSITIONS: (id: string, fromStatus: string) => `/workflows/${id}/transitions/${fromStatus}`,
    },
    COMMENTS: {
        BASE: '/comments',
        BY_ID: (id: string) => `/comments/${id}`,
        BY_TARGET: (targetType: string, targetId: string) => `/comments/target/${targetType}/${targetId}`,
        PARENT: (parentId: string) => `/comments/parent/${parentId}`,
        COUNT: (targetType: string, targetId: string) => `/comments/count/${targetType}/${targetId}`,
    },
    SPACES: {
        BASE: '/spaces',
        BY_ID: (id: string) => `/spaces/${id}`,
        MEMBERS: (id: string) => `/spaces/${id}/members`,
        ADD_MEMBER: (id: string) => `/spaces/${id}/members`,
        REMOVE_MEMBER: (id: string, userId: string) => `/spaces/${id}/members/${userId}`,
    },
    PAGES: {
        BASE: '/pages',
        BY_ID: (id: string) => `/pages/${id}`,
        BY_SLUG: (slug: string) => `/pages/slug/${slug}`,
        BY_SPACE: (spaceId: string) => `/pages/space/${spaceId}`,
        ROOT_PAGES: (spaceId: string) => `/pages/space/${spaceId}/root`,
        BY_PARENT: (parentId: string) => `/pages/parent/${parentId}`,
        BY_AUTHOR: (authorId: string) => `/pages/author/${authorId}`,
        MOVE: (id: string) => `/pages/${id}/move`,
        PUBLISH: (id: string) => `/pages/${id}/publish`,
        UNPUBLISH: (id: string) => `/pages/${id}/unpublish`,
    },
    NOTIFICATIONS: {
        BASE: '/notifications',
        BY_ID: (id: string) => `/notifications/${id}`,
        UNREAD_COUNT: '/notifications/unread/count',
        READ: (id: string) => `/notifications/${id}/read`,
        READ_ALL: '/notifications/read-all',
    },
    DASHBOARD: {
        WORKSPACE: (workspaceId: string) => `/dashboard/workspace/${workspaceId}`,
        PROJECT: (projectId: string) => `/dashboard/project/${projectId}`,
        USER: '/dashboard/user/me',
        SPRINT: (sprintId: string) => `/dashboard/sprint/${sprintId}`,
    },
    SEARCH: {
        BASE: '/search',
        TASKS: '/search/tasks',
        PROJECTS: '/search/projects',
        PAGES: '/search/pages',
    },
    ATTACHMENTS: {
        BASE: '/attachments',
        BY_ID: (id: string) => `/attachments/${id}`,
        DOWNLOAD: (id: string) => `/attachments/${id}/download`,
    },
    USERS: {
        BASE: '/users',
        PROFILE: '/users/profile',
        BY_ID: (id: string) => `/users/${id}`,
        WORKSPACE_MEMBERS: '/workspaces/members',
        ALL: '/users/all',
    },
    INVITE: {
        SEND: '/invite/send',
        ACCEPT: '/invite/accept',
    },
};

export const API_ROUTES = apiRoutes;
